# Generated by Django 3.1.1 on 2020-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
